In [3]:
import numpy as np
nr_array=np.array([[1,5,7,8,9], [2,4,9,6,7],[45,7,6,9,12],[15,36,24,35,14]])
print(nr_array)
arr=nr_array*5
print(arr)
#addition of arrays
print(arr+arr)
#subtraction of arrays 
print(arr-arr)
#dividing 2by array
print(2/arr)
#array raising to the power 3
print(arr**3)

[[ 1  5  7  8  9]
 [ 2  4  9  6  7]
 [45  7  6  9 12]
 [15 36 24 35 14]]
[[  5  25  35  40  45]
 [ 10  20  45  30  35]
 [225  35  30  45  60]
 [ 75 180 120 175  70]]
[[ 10  50  70  80  90]
 [ 20  40  90  60  70]
 [450  70  60  90 120]
 [150 360 240 350 140]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0.4        0.08       0.05714286 0.05       0.04444444]
 [0.2        0.1        0.04444444 0.06666667 0.05714286]
 [0.00888889 0.05714286 0.06666667 0.04444444 0.03333333]
 [0.02666667 0.01111111 0.01666667 0.01142857 0.02857143]]
[[     125    15625    42875    64000    91125]
 [    1000     8000    91125    27000    42875]
 [11390625    42875    27000    91125   216000]
 [  421875  5832000  1728000  5359375   343000]]


In [ ]:
'''Q2: Create a 1D array Arrb of size 20 of any values and perform following operations.
a. Slice the first 4 elements and set them to 0 in the original Array.
b. Slice the last 3 elements and set them 1 but not in the original array'''
import numpy as np
Arrb=np.arange(20)
Arrb

In [ ]:
#first 4 elements
Arrb[0:4]

In [ ]:
#assigning first 4 elements to 0
Arrb[0:4]=0
Arrb

In [ ]:
#b. Slice the last 3 elements and set them 1 but not in the original array.
Arrb[17:20]

In [ ]:
Arrb[17:20]=1
slice_of_a=Arrb[17:20]
slice_of_a

In [1]:
'''Q3: Create a 2D array ‘Arrc’ with dimension 4 and 5 and print the elements of the shaded 
areas.'''
import numpy as np
Arrc=np.array ([[15,48,65,12,32],
                [36,89,25,36,14],
                [36,96,24,12,66],
                [33,96,18,97,45]])
Arrc
print(Arrc[1:3,1:4])
print(Arrc[0:4,0:2])
print(Arrc[0:4,3:4])
print(Arrc[0:3,2:4])
print(Arrc[1:3,4:])

[[89 25 36]
 [96 24 12]]
[[15 48]
 [36 89]
 [36 96]
 [33 96]]
[[12]
 [36]
 [12]
 [97]]
[[65 12]
 [25 36]
 [24 12]]
[[14]
 [66]]


In [ ]:
'''Q4: Create a multidimensional array of shape (4, 2, 5) and perform transpose operation with 
axes (2, 0, 1)'''
M_array=np.arange(40).reshape(4,2,5)
print(M_array)
#transpose of array
A1=M_array.transpose((2,0,1))
print(A1)
A2=M_array.swapaxes()

In [9]:
#Q5: Create a float array and change its type into integer
float_arrc=np.array([12.06, 11.03, 32.21, 18.25])
print(float_arrc)
a=float_arrc.astype(int)
print(a)

[12.06 11.03 32.21 18.25]
[12 11 32 18]


In [17]:
#Q6: Create a 2D array ‘a1’ of shape (3,4) and find the dot product of a1 with a1.
import numpy as np
import numpy.ma as ma
a1=np.random.randint(10,40,size=(3,4))
print(a1)
a1t=np.transpose(a1)
print(a1t)
print(np.dot(a1, a1t))


[[21 26 32 30]
 [30 39 21 24]
 [13 26 29 26]]
[[21 30 13]
 [26 39 26]
 [32 21 29]
 [30 24 26]]
[[3041 3036 2657]
 [3036 3438 2637]
 [2657 2637 2362]]


In [18]:
#Q7: Create an array with all zeros of any size.
trimo=np.zeros((2,4),dtype="int")
print(trimo)

[[0 0 0 0]
 [0 0 0 0]]


In [26]:
# Q8: Create an identity array of any size.
identity_matrix=np.identity(5,dtype="int")
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [41]:
'''Q9: Create an array of size 20 and apply the following functions:
a. Square
b. Ceil
c. Floor
d. Sign
e. Abs'''
dhoni=np.random.randint(-100,100,(1,20))
print(dhoni)
#will ouput the sqare of created array
print(np.square(dhoni))
'''will show the smallest integer greater than or equal to that number'''
print(np.ceil(dhoni))
#will show the largest integer less than or equal to each element)
print(np.floor(dhoni))
#will show the sign of each element: 1 (positive), 0 (zero), or –1 (negative)
print(np.sign(dhoni))
#will give the absolute value element-wise for integer, „oating-point, or complex values
print(np.abs(dhoni))

[[-37  39  27 -25  67 -52 -76  44  30  27 -86 -59 -52 -72  34 -97 -93  30
   68  93]]
[[1369 1521  729  625 4489 2704 5776 1936  900  729 7396 3481 2704 5184
  1156 9409 8649  900 4624 8649]]
[[-37.  39.  27. -25.  67. -52. -76.  44.  30.  27. -86. -59. -52. -72.
   34. -97. -93.  30.  68.  93.]]
[[-37.  39.  27. -25.  67. -52. -76.  44.  30.  27. -86. -59. -52. -72.
   34. -97. -93.  30.  68.  93.]]
[[-1  1  1 -1  1 -1 -1  1  1  1 -1 -1 -1 -1  1 -1 -1  1  1  1]]
[[37 39 27 25 67 52 76 44 30 27 86 59 52 72 34 97 93 30 68 93]]


In [51]:
'''Q10: Create two arrays of same length, include NaN values and perform following 
operations
a. raise elements in the first array to powers indicated in the second array.
b. Perform element wise minimum and ignore NaN.
c. Perform element wise maximum and do not ignore NaN.
d. Subtract the two arrays elements wise.
'''
#first array
A1=np.arange(27,37,dtype="float")
print(A1)
#assigning various indexex to NaN
A1[5]=np.NaN
A1[1]=np.NaN
A1[8]=np.NaN
print(A1,'\n')
#2nd array
A2=np.arange(47,57,dtype="float")
print(A2)
#assigning various indexex to NaN
A2[0]=np.NaN
A2[3]=np.NaN
A2[6]=np.NaN
print(A2,'\n')
#creating new variable arr1
#Raising the power 
arr1=np.power(A1,A2)
print(arr1,'\n')

print(np.nanmin(A1))
print(np.nanmin(A2),'\n')
#Elementwise minimum and ignore Nan
print(np.fmin(A1,A2),'\n')
#Elementwisemaximum with Nan
print(np.maximum(A1,A2),'\n')
#subtract the array  elementwise 
print(np.subtract(A1,A2))

[27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]
[27. nan 29. 30. 31. nan 33. 34. nan 36.] 

[47. 48. 49. 50. 51. 52. 53. 54. 55. 56.]
[nan 48. 49. nan 51. 52. nan 54. 55. 56.] 

[           nan            nan 4.54466522e+71            nan
 1.14669095e+76            nan            nan 5.01027450e+82
            nan 1.42213244e+87] 

27.0
48.0 

[27. 48. 29. 30. 31. 52. 33. 34. 55. 36.] 

[nan nan 49. nan 51. nan nan 54. nan 56.] 

[ nan  nan -20.  nan -20.  nan  nan -20.  nan -20.]
[ nan  nan -20.  nan -20.  nan  nan -20.  nan -20.]


In [56]:
'''Q11: create a two dimensional array of any dimension and replace the values less than 5 
 with -5 and greater than 5 with -1'''
cosmo_array=np.random.randint(1,10,(3,3))
print(cosmo_array) 
cosmo_array > 5
x=np.where(cosmo_array > 5,-1,-5)
print(x)

[[5 7 7]
 [4 3 2]
 [5 7 5]]
[[-5 -1 -1]
 [-5 -5 -5]
 [-5 -1 -5]]


In [52]:
#Q12: create a two dimensional array and find the sum across the column and down the rows.
array_2=np.random.randint(-5,25,(3,5))
print(array_2)
print(array_2.cumsum(axis=0))

[[ 0 14  4 12 12]
 [-3 21 24  3 16]
 [-3  0  2  1 13]]
[[ 0 14  4 12 12]
 [-3 35 28 15 28]
 [-6 35 30 16 41]]


In [67]:
#Q13: Create a two dimensional array and find the cumulative product across the columns and down the rows.
array_1 = np.random.randint(10,45,(4,4))
print(array_1)
# compute the cummulative product of 2D array
#store the  comulative product in np_array_cumprod
np_array_cumprod = np.cumprod(array_1, axis=0)

print(np_array_cumprod)

[[39 41 26 39]
 [26 13 14 14]
 [14 12 18 42]
 [38 21 26 14]]
[[    39     41     26     39]
 [  1014    533    364    546]
 [ 14196   6396   6552  22932]
 [539448 134316 170352 321048]]


In [3]:
'''Q14: Create a two dimensional array and sort the elements across the columns and down 
the rows. Also, sort all the elements and convert them into a one dimensional array.'''
import numpy as np
ps1=np.random.randint(-15,12,(4,4))
print(ps1)
ps1.sort(0)
print(ps1)
x=ps1.reshape(1,16)
print(x)

[[ -6   7  -6   0]
 [  2 -10   3 -15]
 [-14 -14 -11 -15]
 [  4 -11  -1  11]]
[[-14 -14 -11 -15]
 [ -6 -11  -6 -15]
 [  2 -10  -1   0]
 [  4   7   3  11]]
[[-14 -14 -11 -15  -6 -11  -6 -15   2 -10  -1   0   4   7   3  11]]


In [92]:
'''Q15: Take two one dimensional arrays, x and y, and perform:
a. Find common elements in x and y
b. Find the sorted union of elements of x and y.
c. Find a Boolean array indicating whether each element of x is contained in y
d. Find elements in x that are not in y
e. Find elements that are in either of the arrays, but not both'''
#ist array
x=np.random.randint(-10,20,(1,9))
print(x)
#2nd array
y=np.random.randint(-10,20,(1,9))
print(y)
#showing common elements
common_e=np.intersect1d(x,y)
print(common_e)
#sorted union of elements of x and y
print(np.union1d(x,y)) 
#will show the boolean array indicating whether each element of x is contained in y
print(np.in1d(x,y))
#will find unique elements of x
print(np.unique(x))
#will give the universal elements
print(np.setxor1d(x,y))

[[19 13 -3 14 -1 18 19  8 13]]
[[16 10  9 -2 -6 -1  6  1  1]]
[-1]
[-6 -3 -2 -1  1  6  8  9 10 13 14 16 18 19]
[False False False False  True False False False False]
[-3 -1  8 13 14 18 19]
[-6 -3 -2  1  6  8  9 10 13 14 16 18 19]
